In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_parquet(r'C:\Users\marco\Desktop\ProyectoGrupalH\dataparquet\data_productsP')
df

,product_category_name_english,product_id,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,health_beauty,e3e020af31d4d89d2602272b315c3f6e,3.0,75.0,21.0,7.0,13.0
1,health_beauty,c5d8079278e912d7e3b6beb48ecb56e8,1.0,1300.0,19.0,28.0,17.0
2,health_beauty,36555a2f528d7b2a255c504191445d39,1.0,1467.0,23.0,16.0,20.0
3,health_beauty,e586ebb6022265ae1eea38f46ffe3ead,3.0,1050.0,18.0,21.0,27.0
4,health_beauty,75b4372e69a42f8ae1d908c076f547b2,1.0,938.0,29.0,22.0,23.0
...,...,...,...,...,...,...,...
32323,fashion_childrens_clothes,2b18330ce86ae5c606250b75b499f370,3.0,120.0,19.0,11.0,15.0
32324,fashion_childrens_clothes,28ac6af4008a402e5039f3e042a36e13,5.0,500.0,36.0,10.0,26.0
32325,fashion_childrens_clothes,57bdf3098169cccdb62221bd3e089cbd,1.0,100.0,16.0,16.0,16.0
32326,security_and_services,8db75af9aed3315374db44d7860e25da,4.0,400.0,26.0,22.0,11.0
32327,security_and_services,6c7a0a349ad11817745e3ad58abd5c79,1.0,1225.0,27.0,35.0,15.0

In [18]:
df[df['product_width_cm'] == 'sin_categoria']

Empty DataFrame
Columns: [product_category_name_english, product_id, product_photos_qty, product_weight_g, product_length_cm, product_height_cm, product_width_cm]
Index: []